#ifndef TIME_CAST_DEFINES_HPP
#define TIME_CAST_DEFINES_HPP

#define TIMECAST_HOUR "%H"
#define TIMECAST_MINUTE "%M"
#define TIMECAST_SECOND "%S"
#define TIMECAST_TIME "%T"
#define TIMECAST_SHORT_TIME "%R"
#define TIMECAST_YEAR "%Y"
#define TIMECAST_MONTH "%m"
#define TIMECAST_DAY "%d"
#define TIMECAST_DATE "%F"
#define TIMECAST_LOCAL_TIME "%X"
#define TIMECAST_LOCAL_DATE "%x"
#define TIMECAST_LOCAL_DATETIME "%c"
#define TIMECAST_EPOCH "%s"

#endif
